version: "3"
services:
  prod:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: winebot
    depends_on:
      - mongo
    env_file:
      - .env
    cpus: 0.4  
  mongo:
    restart: always
    image: mongo:latest
    container_name: winebot-mongo
    cpus: 0.3  
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo-data:/data/db
  admin:
    build:
      context: ./admin/
    restart: always
    container_name: winebot-admin
    env_file:
      - .env
    ports:
      - "8000:8000"
    cpus: 0.3
volumes:
  mongo-data:
    driver: local